// PAGE 5 ICONS
import benefitPageLogo_1 from "../src/images/page_5_icons/Page_5_1.png";
import benefitPageLogo_2 from "../src/images/page_5_icons/Page_5_2.png";
import benefitPageLogo_3 from "../src/images/page_5_icons/Page_5_3.png";
import benefitPageLogo_4 from "../src/images/page_5_icons/Page_5_4.png";
import benefitPageLogo_5 from "../src/images/page_5_icons/Page_5_5.png";

// PAGE 6 ICONS
import gridPageLogo_1 from "../src/images/page_6_icons/Page_6_1.png";
import gridPageLogo_2 from "../src/images/page_6_icons/Page_6_2.png";
import gridPageLogo_3 from "../src/images/page_6_icons/Page_6_3.png";
import gridPageLogo_4 from "../src/images/page_6_icons/Page_6_4.png";
import gridPageLogo_5 from "../src/images/page_6_icons/Page_6_5.png";

export const countries = [
  { name: "Afghanistan", value: "AF" },
  { name: "Åland Islands", value: "AX" },
  { name: "Albania", value: "AL" },
  { name: "Algeria", value: "DZ" },
  { name: "American Samoa", value: "AS" },
  { name: "Andorra", value: "AD" },
  { name: "Angola", value: "AO" },
  { name: "Anguilla", value: "AI" },
  { name: "Antarctica", value: "AQ" },
  { name: "Antigua and Barbuda", value: "AG" },
  { name: "Argentina", value: "AR" },
  { name: "Armenia", value: "AM" },
  { name: "Aruba", value: "AW" },
  { name: "Australia", value: "AU" },
  { name: "Austria", value: "AT" },
  { name: "Azerbaijan", value: "AZ" },
  { name: "Bahamas", value: "BS" },
  { name: "Bahrain", value: "BH" },
  { name: "Bangladesh", value: "BD" },
  { name: "Barbados", value: "BB" },
  { name: "Belarus", value: "BY" },
  { name: "Belgium", value: "BE" },
  { name: "Belize", value: "BZ" },
  { name: "Benin", value: "BJ" },
  { name: "Bermuda", value: "BM" },
  { name: "Bhutan", value: "BT" },
  { name: "Bolivia", value: "BO" },
  { name: "Bosnia and Herzegovina", value: "BA" },
  { name: "Botswana", value: "BW" },
  { name: "Bouvet Island", value: "BV" },
  { name: "Brazil", value: "BR" },
  { name: "British Indian Ocean Territory", value: "IO" },
  { name: "Brunei Darussalam", value: "BN" },
  { name: "Bulgaria", value: "BG" },
  { name: "Burkina Faso", value: "BF" },
  { name: "Burundi", value: "BI" },
  { name: "Cambodia", value: "KH" },
  { name: "Cameroon", value: "CM" },
  { name: "Canada", value: "CA" },
  { name: "Cape Verde", value: "CV" },
  { name: "Cayman Islands", value: "KY" },
  { name: "Central African Republic", value: "CF" },
  { name: "Chad", value: "TD" },
  { name: "Chile", value: "CL" },
  { name: "China", value: "CN" },
  { name: "Christmas Island", value: "CX" },
  { name: "Cocos (Keeling) Islands", value: "CC" },
  { name: "Colombia", value: "CO" },
  { name: "Comoros", value: "KM" },
  { name: "Congo", value: "CG" },
  { name: "Congo, The Democratic Republic of the", value: "CD" },
  { name: "Cook Islands", value: "CK" },
  { name: "Costa Rica", value: "CR" },
  { name: "Cote D'Ivoire", value: "CI" },
  { name: "Croatia", value: "HR" },
  { name: "Cuba", value: "CU" },
  { name: "Cyprus", value: "CY" },
  { name: "Czech Republic", value: "CZ" },
  { name: "Denmark", value: "DK" },
  { name: "Djibouti", value: "DJ" },
  { name: "Dominica", value: "DM" },
  { name: "Dominican Republic", value: "DO" },
  { name: "Ecuador", value: "EC" },
  { name: "Egypt", value: "EG" },
  { name: "El Salvador", value: "SV" },
  { name: "Equatorial Guinea", value: "GQ" },
  { name: "Eritrea", value: "ER" },
  { name: "Estonia", value: "EE" },
  { name: "Ethiopia", value: "ET" },
  { name: "Falkland Islands (Malvinas)", value: "FK" },
  { name: "Faroe Islands", value: "FO" },
  { name: "Fiji", value: "FJ" },
  { name: "Finland", value: "FI" },
  { name: "France", value: "FR" },
  { name: "French Guiana", value: "GF" },
  { name: "French Polynesia", value: "PF" },
  { name: "French Southern Territories", value: "TF" },
  { name: "Gabon", value: "GA" },
  { name: "Gambia", value: "GM" },
  { name: "Georgia", value: "GE" },
  { name: "Germany", value: "DE" },
  { name: "Ghana", value: "GH" },
  { name: "Gibraltar", value: "GI" },
  { name: "Greece", value: "GR" },
  { name: "Greenland", value: "GL" },
  { name: "Grenada", value: "GD" },
  { name: "Guadeloupe", value: "GP" },
  { name: "Guam", value: "GU" },
  { name: "Guatemala", value: "GT" },
  { name: "Guernsey", value: "GG" },
  { name: "Guinea", value: "GN" },
  { name: "Guinea-Bissau", value: "GW" },
  { name: "Guyana", value: "GY" },
  { name: "Haiti", value: "HT" },
  { name: "Heard Island and Mcdonald Islands", value: "HM" },
  { name: "Holy See (Vatican City State)", value: "VA" },
  { name: "Honduras", value: "HN" },
  { name: "Hong Kong", value: "HK" },
  { name: "Hungary", value: "HU" },
  { name: "Iceland", value: "IS" },
  { name: "India", value: "IN" },
  { name: "Indonesia", value: "ID" },
  { name: "Iran, Islamic Republic Of", value: "IR" },
  { name: "Iraq", value: "IQ" },
  { name: "Ireland", value: "IE" },
  { name: "Isle of Man", value: "IM" },
  { name: "Israel", value: "IL" },
  { name: "Italy", value: "IT" },
  { name: "Jamaica", value: "JM" },
  { name: "Japan", value: "JP" },
  { name: "Jersey", value: "JE" },
  { name: "Jordan", value: "JO" },
  { name: "Kazakhstan", value: "KZ" },
  { name: "Kenya", value: "KE" },
  { name: "Kiribati", value: "KI" },
  { name: "Korea, Democratic People'S Republic of", value: "KP" },
  { name: "Korea, Republic of", value: "KR" },
  { name: "Kuwait", value: "KW" },
  { name: "Kyrgyzstan", value: "KG" },
  { name: "Lao People'S Democratic Republic", value: "LA" },
  { name: "Latvia", value: "LV" },
  { name: "Lebanon", value: "LB" },
  { name: "Lesotho", value: "LS" },
  { name: "Liberia", value: "LR" },
  { name: "Libyan Arab Jamahiriya", value: "LY" },
  { name: "Liechtenstein", value: "LI" },
  { name: "Lithuania", value: "LT" },
  { name: "Luxembourg", value: "LU" },
  { name: "Macao", value: "MO" },
  { name: "Macedonia, The Former Yugoslav Republic of", value: "MK" },
  { name: "Madagascar", value: "MG" },
  { name: "Malawi", value: "MW" },
  { name: "Malaysia", value: "MY" },
  { name: "Maldives", value: "MV" },
  { name: "Mali", value: "ML" },
  { name: "Malta", value: "MT" },
  { name: "Marshall Islands", value: "MH" },
  { name: "Martinique", value: "MQ" },
  { name: "Mauritania", value: "MR" },
  { name: "Mauritius", value: "MU" },
  { name: "Mayotte", value: "YT" },
  { name: "Mexico", value: "MX" },
  { name: "Micronesia, Federated States of", value: "FM" },
  { name: "Moldova, Republic of", value: "MD" },
  { name: "Monaco", value: "MC" },
  { name: "Mongolia", value: "MN" },
  { name: "Montserrat", value: "MS" },
  { name: "Morocco", value: "MA" },
  { name: "Mozambique", value: "MZ" },
  { name: "Myanmar", value: "MM" },
  { name: "Namibia", value: "NA" },
  { name: "Nauru", value: "NR" },
  { name: "Nepal", value: "NP" },
  { name: "Netherlands", value: "NL" },
  { name: "Netherlands Antilles", value: "AN" },
  { name: "New Caledonia", value: "NC" },
  { name: "New Zealand", value: "NZ" },
  { name: "Nicaragua", value: "NI" },
  { name: "Niger", value: "NE" },
  { name: "Nigeria", value: "NG" },
  { name: "Niue", value: "NU" },
  { name: "Norfolk Island", value: "NF" },
  { name: "Northern Mariana Islands", value: "MP" },
  { name: "Norway", value: "NO" },
  { name: "Oman", value: "OM" },
  { name: "Pakistan", value: "PK" },
  { name: "Palau", value: "PW" },
  { name: "Palestinian Territory, Occupied", value: "PS" },
  { name: "Panama", value: "PA" },
  { name: "Papua New Guinea", value: "PG" },
  { name: "Paraguay", value: "PY" },
  { name: "Peru", value: "PE" },
  { name: "Philippines", value: "PH" },
  { name: "Pitcairn", value: "PN" },
  { name: "Poland", value: "PL" },
  { name: "Portugal", value: "PT" },
  { name: "Puerto Rico", value: "PR" },
  { name: "Qatar", value: "QA" },
  { name: "Reunion", value: "RE" },
  { name: "Romania", value: "RO" },
  { name: "Russian Federation", value: "RU" },
  { name: "RWANDA", value: "RW" },
  { name: "Saint Helena", value: "SH" },
  { name: "Saint Kitts and Nevis", value: "KN" },
  { name: "Saint Lucia", value: "LC" },
  { name: "Saint Pierre and Miquelon", value: "PM" },
  { name: "Saint Vincent and the Grenadines", value: "VC" },
  { name: "Samoa", value: "WS" },
  { name: "San Marino", value: "SM" },
  { name: "Sao Tome and Principe", value: "ST" },
  { name: "Saudi Arabia", value: "SA" },
  { name: "Senegal", value: "SN" },
  { name: "Serbia and Montenegro", value: "CS" },
  { name: "Seychelles", value: "SC" },
  { name: "Sierra Leone", value: "SL" },
  { name: "Singapore", value: "SG" },
  { name: "Slovakia", value: "SK" },
  { name: "Slovenia", value: "SI" },
  { name: "Solomon Islands", value: "SB" },
  { name: "Somalia", value: "SO" },
  { name: "South Africa", value: "ZA" },
  { name: "South Georgia and the South Sandwich Islands", value: "GS" },
  { name: "Spain", value: "ES" },
  { name: "Sri Lanka", value: "LK" },
  { name: "Sudan", value: "SD" },
  { name: "Suriname", value: "SR" },
  { name: "Svalbard and Jan Mayen", value: "SJ" },
  { name: "Swaziland", value: "SZ" },
  { name: "Sweden", value: "SE" },
  { name: "Switzerland", value: "CH" },
  { name: "Syrian Arab Republic", value: "SY" },
  { name: "Taiwan, Province of China", value: "TW" },
  { name: "Tajikistan", value: "TJ" },
  { name: "Tanzania, United Republic of", value: "TZ" },
  { name: "Thailand", value: "TH" },
  { name: "Timor-Leste", value: "TL" },
  { name: "Togo", value: "TG" },
  { name: "Tokelau", value: "TK" },
  { name: "Tonga", value: "TO" },
  { name: "Trinidad and Tobago", value: "TT" },
  { name: "Tunisia", value: "TN" },
  { name: "Turkey", value: "TR" },
  { name: "Turkmenistan", value: "TM" },
  { name: "Turks and Caicos Islands", value: "TC" },
  { name: "Tuvalu", value: "TV" },
  { name: "Uganda", value: "UG" },
  { name: "Ukraine", value: "UA" },
  { name: "United Arab Emirates", value: "AE" },
  { name: "United Kingdom", value: "GB" },
  { name: "United States", value: "US" },
  { name: "United States Minor Outlying Islands", value: "UM" },
  { name: "Uruguay", value: "UY" },
  { name: "Uzbekistan", value: "UZ" },
  { name: "Vanuatu", value: "VU" },
  { name: "Venezuela", value: "VE" },
  { name: "Viet Nam", value: "VN" },
  { name: "Virgin Islands, British", value: "VG" },
  { name: "Virgin Islands, U.S.", value: "VI" },
  { name: "Wallis and Futuna", value: "WF" },
  { name: "Western Sahara", value: "EH" },
  { name: "Yemen", value: "YE" },
  { name: "Zambia", value: "ZM" },
  { name: "Zimbabwe", value: "ZW" },
];

export const trainingOptions = [
  { value: "web-development", name: "Web Development" },
  { value: "data-science", name: "Data Science" },
  { value: "digital-marketing", name: "Digital Marketing" },
  { value: "graphic-design", name: "Graphic Design" },
  { value: "software-engineering", name: "Software Engineering" },
  { value: "machine-learning", name: "Machine Learning" },
  { value: "cyber-security", name: "Cyber Security" },
  { value: "cloud-computing", name: "Cloud Computing" },
  { value: "ux-ui-design", name: "UX/UI Design" },
  { value: "seo", name: "Search Engine Optimization (SEO)" },
  { value: "project-management", name: "Project Management" },
  { value: "mobile-development", name: "Mobile Development" },
  { value: "java-programming", name: "Java Programming" },
  { value: "python-programming", name: "Python Programming" },
  { value: "full-stack-development", name: "Full Stack Development" },
  { value: "data-analytics", name: "Data Analytics" },
  { value: "artificial-intelligence", name: "Artificial Intelligence" },
  { value: "blockchain", name: "Blockchain" },
  { value: "business-intelligence", name: "Business Intelligence" },
  { value: "devops", name: "DevOps" },
  { value: "ios-development", name: "iOS Development" },
  { value: "android-development", name: "Android Development" },
  { value: "game-development", name: "Game Development" },
  { value: "virtual-reality", name: "Virtual Reality" },
  { value: "agile-methodology", name: "Agile Methodology" },
  { value: "sqa", name: "Software Quality Assurance" },
  { value: "cloud-architecture", name: "Cloud Architecture" },
  { value: "reactjs", name: "ReactJS Development" },
  { value: "angularjs", name: "AngularJS Development" },
];

export const coursesOptions = [
  { value: "frontend-development", name: "Frontend Development" },
  { value: "backend-development", name: "Backend Development" },
  { value: "data-analysis", name: "Data Analysis" },
  { value: "machine-learning-ai", name: "Machine Learning & AI" },
  { value: "big-data", name: "Big Data" },
  { value: "python-for-data-science", name: "Python for Data Science" },
  { value: "cloud-services", name: "Cloud Services" },
  { value: "android-app-development", name: "Android App Development" },
  { value: "ios-app-development", name: "iOS App Development" },
  {
    value: "digital-marketing-fundamentals",
    name: "Digital Marketing Fundamentals",
  },
  { value: "seo-basics", name: "SEO Basics" },
  { value: "java-development", name: "Java Development" },
  { value: "c-sharp-development", name: "C# Development" },
  { value: "full-stack-web-development", name: "Full Stack Web Development" },
  { value: "java-spring-framework", name: "Java Spring Framework" },
  { value: "mern-stack", name: "MERN Stack Development" },
  { value: "reactjs-course", name: "ReactJS Course" },
  { value: "angular-development", name: "Angular Development" },
  { value: "vuejs-development", name: "VueJS Development" },
  { value: "ethical-hacking", name: "Ethical Hacking" },
  { value: "cyber-security-foundations", name: "Cyber Security Foundations" },
  { value: "ux-ui-design-principles", name: "UX/UI Design Principles" },
  { value: "web-accessibility", name: "Web Accessibility" },
  {
    value: "game-development-with-unity",
    name: "Game Development with Unity",
  },
  { value: "blockchain-basics", name: "Blockchain Basics" },
  { value: "data-visualization", name: "Data Visualization" },
  { value: "business-analysis", name: "Business Analysis" },
  {
    value: "project-management-certification",
    name: "Project Management Certification",
  },
  { value: "agile-scrum-methodology", name: "Agile Scrum Methodology" },
  {
    value: "sqa-certification",
    name: "Software Quality Assurance Certification",
  },
];

export const program_Cards = [
  {
    id: 1,
    price: "₹22,500",
    name: "ISO 9001:2015 Lead Auditor Training Course",
    category: "Quality Management",
    date: "3 March 25 to 19 March 25",
    language: "English",
    mode: "Virtual",
  },
  {
    id: 2,
    price: "₹2,500",
    name: "ISO 9001:2015 Lead Auditor Training Course",
    category: "Quality Management",
    date: "3 March 25 to 19 March 25",
    language: "English",
    mode: "Virtual",
  },
  {
    id: 3,
    price: "₹32,500",
    name: "ISO 9001:2015 Lead Auditor Training Course",
    category: "Quality Management",
    date: "3 March 25 to 19 March 25",
    language: "English",
    mode: "Virtual",
  },
  {
    id: 4,
    price: "₹32,500",
    name: "ISO 9001:2015 Lead Auditor Training Course",
    category: "Quality Management",
    date: "3 March 25 to 19 March 25",
    language: "English",
    mode: "Virtual",
  },
];

export const benefits_Card = [
  {
    id: 1,
    first: "Cost-Effective",
    second: "Training Solution",
    description:
      "Reduce costs per participant through group pricing, making it more affordable than individual enrolments. Virtual or on-site delivery eliminates travel and accommodation expenses. Customized programs accelerate compliance and boost  efficiency. Achieve a faster return on investment with tailored, business-focused learning.",
    color: "#fe83b0",
    logo: benefitPageLogo_1,
  },
  {
    id: 2,
    first: "Minimal",
    second: "Business Disruption",
    description:
      "Our solution ensures minimal business disruption by offering flexible virtual or on-site delivery, allowing teams to learn without significant interruption. Tailored programs align with your business needs, promoting efficiency and seamless integration.",
    color: "#9d8dfb",
    logo: benefitPageLogo_2,
  },
  {
    id: 3,
    first: "Tailored for your",
    second: "Industry & Team",
    description:
      "Our programs are tailored specifically for your industry and team, addressing unique challenges and goals. This customized approach ensures relevant learning, improving skills and driving success within your organization.",
    color: "#6fdaf5",
    logo: benefitPageLogo_3,
  },
  {
    id: 4,
    first: "Confidential &",
    second: "Secure Learning",
    description:
      "Our programs prioritize confidentiality and security, ensuring that all learning materials and participant information are protected. You can trust us to provide a safe and secure learning environment for your team.",
    color: "#ffb560",
    logo: benefitPageLogo_4,
  },
  {
    id: 5,
    first: "Flexible ",
    second: "Delivery Options",
    description:
      "We offer flexible delivery options, including virtual and on-site formats, allowing you to choose the best method for your team’s needs and schedule, ensuring convenience and accessibility.",
    color: "#64d1af",
    logo: benefitPageLogo_5,
  },
];

export const gridDetails = [
  {
    id: 1,
    title: "Greater Knowledge Transfer & Practical Application",
    description:
      "Employees learn best when they can connect training to their daily tasks. Our in-house programs align course content with your company's systems, policies, and workflows, ensuring that training is immediately applicable.",
    logo: gridPageLogo_1,
  },
  {
    id: 2,
    title: "Stronger Teamwork & Company-Wide Alignment",
    description:
      "When employees train together, they develop a shared understanding of business goals, processes, and compliance requirements. This enhances collaboration, efficiency, and overall team performance.",
    logo: gridPageLogo_2,
  },
  {
    id: 3,
    title: "Higher Retention & ROI on Training Investment",
    description:
      "Teams trained in-house retain more knowledge and engage better than those in external courses. This fosters active participation, knowledge-sharing, and higher ROI.",
    logo: gridPageLogo_3,
  },
  {
    id: 4,
    title: "Industry-Specific & Custom-Designed Courses",
    description:
      "Your business is unique—your training should be too. We tailor courses to your industry's regulations, ISO standards, and operational needs, ensuring that training adds real your organization.",
    logo: gridPageLogo_4,
  },
  {
    id: 5,
    title: "Convenience & Maximum Flexibility",
    description:
      "Whether your team prefers onsite, online, or hybrid training, we work around your schedule to provide a seamless learning experience. You decide when and how training happens—we make it easy.",
    logo: gridPageLogo_5,
  },
];

export const form_Object = {
  full_name: "",
  email: "",
  training: "",
  course: "",
  country: "",
  message: "",
};
